_target_: sn_gamestate.calibration.nbjw_calib.NBJW_Calib_Keypoints
checkpoint_kp: ${model_dir}/calibration/SV_kp
checkpoint_l: ${model_dir}/calibration/SV_lines
image_width: 1920
image_height: 1080
batch_size: 1


#Kp model
cfg:
  MODEL:
    IMAGE_SIZE: [960, 540]
    NUM_JOINTS: 58
    PRETRAIN: ''
    EXTRA:
      FINAL_CONV_KERNEL: 1
      STAGE1:
        NUM_MODULES: 1
        NUM_BRANCHES: 1
        BLOCK: BOTTLENECK
        NUM_BLOCKS: [4]
        NUM_CHANNELS: [64]
        FUSE_METHOD: SUM
      STAGE2:
        NUM_MODULES: 1
        NUM_BRANCHES: 2
        BLOCK: BASIC
        NUM_BLOCKS: [4, 4]
        NUM_CHANNELS: [48, 96]
        FUSE_METHOD: SUM
      STAGE3:
        NUM_MODULES: 4
        NUM_BRANCHES: 3
        BLOCK: BASIC
        NUM_BLOCKS: [4, 4, 4]
        NUM_CHANNELS: [48, 96, 192]
        FUSE_METHOD: SUM
      STAGE4:
        NUM_MODULES: 3
        NUM_BRANCHES: 4
        BLOCK: BASIC
        NUM_BLOCKS: [4, 4, 4, 4]
        NUM_CHANNELS: [48, 96, 192, 384]
        FUSE_METHOD: SUM


#line model
cfg_l:
  MODEL:
    IMAGE_SIZE: [ 960, 540 ]
    NUM_JOINTS: 24
    PRETRAIN: ''
    EXTRA:
      FINAL_CONV_KERNEL: 1
      STAGE1:
        NUM_MODULES: 1
        NUM_BRANCHES: 1
        BLOCK: BOTTLENECK
        NUM_BLOCKS: [ 4 ]
        NUM_CHANNELS: [ 64 ]
        FUSE_METHOD: SUM
      STAGE2:
        NUM_MODULES: 1
        NUM_BRANCHES: 2
        BLOCK: BASIC
        NUM_BLOCKS: [ 4, 4 ]
        NUM_CHANNELS: [ 48, 96 ]
        FUSE_METHOD: SUM
      STAGE3:
        NUM_MODULES: 4
        NUM_BRANCHES: 3
        BLOCK: BASIC
        NUM_BLOCKS: [ 4, 4, 4 ]
        NUM_CHANNELS: [ 48, 96, 192 ]
        FUSE_METHOD: SUM
      STAGE4:
        NUM_MODULES: 3
        NUM_BRANCHES: 4
        BLOCK: BASIC
        NUM_BLOCKS: [ 4, 4, 4, 4 ]
        NUM_CHANNELS: [ 48, 96, 192, 384 ]
        FUSE_METHOD: SUM


